// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFOHCT2BDebqMouas_rG7U7w7o7nLY_M',
    appId: '1:377343513638:web:59cb055aa3145781f142e7',
    messagingSenderId: '377343513638',
    projectId: 'todoji-3f9fe',
    authDomain: 'todoji-3f9fe.firebaseapp.com',
    storageBucket: 'todoji-3f9fe.firebasestorage.app',
    measurementId: 'G-W6GCMR77C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFGzC2IGYq2FOZxisp2JzYpwZOg9-frY',
    appId: '1:377343513638:android:d8e81669d85a0fabf142e7',
    messagingSenderId: '377343513638',
    projectId: 'todoji-3f9fe',
    storageBucket: 'todoji-3f9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0qnE-ome8EYztXmXMD3KP_QgmyzA6wOo',
    appId: '1:377343513638:ios:357c96b5222fe555f142e7',
    messagingSenderId: '377343513638',
    projectId: 'todoji-3f9fe',
    storageBucket: 'todoji-3f9fe.firebasestorage.app',
    iosBundleId: 'com.example.todoJi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0qnE-ome8EYztXmXMD3KP_QgmyzA6wOo',
    appId: '1:377343513638:ios:357c96b5222fe555f142e7',
    messagingSenderId: '377343513638',
    projectId: 'todoji-3f9fe',
    storageBucket: 'todoji-3f9fe.firebasestorage.app',
    iosBundleId: 'com.example.todoJi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWFOHCT2BDebqMouas_rG7U7w7o7nLY_M',
    appId: '1:377343513638:web:21088e667e6c4cd2f142e7',
    messagingSenderId: '377343513638',
    projectId: 'todoji-3f9fe',
    authDomain: 'todoji-3f9fe.firebaseapp.com',
    storageBucket: 'todoji-3f9fe.firebasestorage.app',
    measurementId: 'G-RWX4HKG5V1',
  );
}
